Aruba.Eis/Models/Bl/Activity.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Aruba.Eis.Models.Bl
{
    public class Activity
    {
        public int Id { get; set; }

        [Required]
        public string Code { get; set; }

        [Required]
        public string Name { get; set; }

        public IList<ActivityResource> Resources { get; set; }
    }
}

Aruba.Eis/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Aruba.Eis.EntityFramework;
using Aruba.Eis.Models.Entities;
using Aruba.Eis.Models.Views;
using log4net;
using Aruba.Eis.Services;
using Aruba.Eis.Models.Bl;
using Aruba.Eis.Helpers;

namespace Aruba.Eis.Controllers
{
    [Authorize(Roles = Role.Manager)]
    public class ActivityController : Controller
    {
        /// <summary>
        /// Log Manager
        /// </summary>
        private static readonly ILog Log =
            LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        /// <summary>
        /// Dependencies
        /// </summary>
        private IActivityService ActivityService { get; set; }

        /// <summary>
        /// Team Controller constructor
        /// </summary>
        public ActivityController(IActivityService activityService)
        {
            // DI
            ActivityService = activityService;
        }

        //
        // GET: /Activity/Index
        //
        public async Task<ActionResult> Index()
        {
            var model = new ActivityIndexViewModel();
            model.ActivityList = await ActivityService.Search();
            return View(model);
        }

        //
        // POST: /Activity/Index
        //
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(ActivityIndexViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var filter = model.Filter;
                model.ActivityList = await ActivityService.Search(filter);
            }
            catch (Exception e)
            {
                Log.Error("Activity Index Error", e);
                ModelState.AddModelError("", "ERRORE!");
            }
            return View(model);
        }

        //
        // GET: /Activity/Create
        //
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Activity/Create
        //
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Code,Name")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                await ActivityService.Create(activity);
                return RedirectToAction("Index");
            }

            return View(activity);
        }

        //
        // GET: /Activity/Edit/5
        //
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            await HtmlItems.LoadRoleListItems();
            var activity = await ActivityService.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        //
        // POST: /Activity/Edit/5
        //
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Code,Name,Resources")] Activity activity)
        {
            foreach (var key in ModelState.Keys)
            {
                if (key.EndsWith("Role.Name"))
                    ModelState[key].Errors.Clear();
            }
            if (ModelState.IsValid)
            {
                await ActivityService.Save(activity);
                return RedirectToAction("Index");
            }
            return View(activity);
        }

        //
        // GET: /Activity/Delete/5
        //
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = await ActivityService.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        //
        // POST: /Activity/Delete/5
        //
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await ActivityService.Remove(id);
            return RedirectToAction("Index");
        }

        //
        // GET: /Activity/AddResource
        //
        public PartialViewResult AddResource()
        {
            var model = new ActivityResource();
            model.RoleId = "";
            return PartialView("_Resources", model);
        }
    }
}

Aruba.Eis/Views/Activity/Create.cshtml
@model Aruba.Eis.Models.Bl.Activity
@using Aruba.Eis
@{
    ViewBag.Title = I18nResource.NEW_ACTIVITY;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@I18nResource.CREATE" class="btn btn-warning" />
                @Html.ActionLink(I18nResource.CANCEL, "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}


Aruba.Eis/Views/Activity/Delete.cshtml
@model Aruba.Eis.Models.Bl.Activity
@using Aruba.Eis
@{
    ViewBag.Title = I18nResource.DELETE_ACTIVITY;
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>
    
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
    
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    
    </dl>
    
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <h3>@I18nResource.CONFIRM_DELETE</h3>

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-warning" />
            @Html.ActionLink(I18nResource.CANCEL, "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>


Aruba.Eis/Views/Activity/Edit.cshtml
@model Aruba.Eis.Models.Bl.Activity
@using Aruba.Eis
@using Aruba.MvcToolkit.Html
@{
    ViewBag.Title = I18nResource.EDIT_ACTIVITY;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Code, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@I18nResource.SAVE" class="btn btn-warning"/>
                @Html.ActionLink(I18nResource.CANCEL, "Index", null, new {@class = "btn btn-default"})
            </div>
        </div>

        <table id="Resources" class="table">
            <thead>
            <tr>
                <th>Role</th>
                <th>MinOccurs</th>
                <th>MaxOccurs</th>
                <th></th>
            </tr>
            </thead>
            @Html.CollectionEditorFor(m => m.Resources, "_Resources", "/Activity/AddResource",
                "Add Resource", new {@class = "btn btn-default"})
        </table>

    </div>

}

Aruba.Eis/Views/Activity/Index.cshtml
@model Aruba.Eis.Models.Views.ActivityIndexViewModel
@using Aruba.Eis
@{
    ViewBag.Title = I18nResource.ACTIVITIES;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Index", "Activity", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <p>
        @Html.ActionLink(@I18nResource.NEW, "Create", null, new { @class = "btn btn-warning" })
    </p>
    <table class="table">
        <tr>
            <th>
                @I18nResource.CODE
            </th>
            <th>
                @I18nResource.NAME
            </th>
            <th></th>
        </tr>
        <tr>
            <td colspan="2">
                @Html.TextBoxFor(m => m.Filter, new { @class = "form-control", placeholder = I18nResource.FILTER, maxlength = 50 })
            </td>
            <td>
                <input type="submit" class="btn btn-default" value="@I18nResource.SEARCH" />
            </td>
        </tr>

        @foreach (var item in Model.ActivityList)
        {
            <tr>
                <td>
                    @item.Code
                </td>
                <td>
                    @item.Name
                </td>
                <td>
                    @Html.ActionLink(I18nResource.EDIT, "Edit", new { id = item.Id }) |
                    @Html.ActionLink(I18nResource.DELETE, "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
}    


Aruba.Eis/Views/Activity/_Resources.cshtml
@model Aruba.Eis.Models.Bl.ActivityResource
@using HtmlHelpers.BeginCollectionItem
@using Aruba.Eis.Helpers

@{
    var roles = HtmlItems.RoleListItems;
}

<tr>
    @using (Html.BeginCollectionItem("Resources"))
    {
        @Html.HiddenFor(m => m.Id)
        <td>
            @Html.DropDownListFor(m => m.RoleId, roles, "-- Select Role --", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
        </td>
        <td>
            @Html.TextBox("MinOccurs", @Model.MinOccurs, new { @class = "form-control", size = "5" })
            @Html.ValidationMessageFor(model => model.MinOccurs, "", new { @class = "text-danger" })
        </td>
        <td>
            @Html.TextBox("MaxOccurs", @Model.MaxOccurs, new { @class = "form-control", size = "5" })
            @Html.ValidationMessageFor(model => model.MaxOccurs, "", new { @class = "text-danger" })
        </td>
        <td>
            <input type="button" value="Delete" class="btn btn-default"
                   onclick="$(this).parent().parent().remove();" />
        </td>
    }
</tr>